name: jh_flutter_demo
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.3.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 三方库管理
  # 网站1：https://pub.flutter-io.cn
  # 网站2：https://pub.dev
  # dart 2.12 之后需要处理空安全
  # ^ 表示 大版本不变，小版本使用最新的版本
  # 三方库冲突时使用 any ，执行 flutter pub get命令，然后在pubspec.lock替换版本号
  # 三方库未适配空安全，点击main.dart -> Additional arguments 添加 --no-sound-null-safety

  # 网络请求 https://pub.flutter-io.cn/packages/dio
  dio: ^4.0.6
  #  # 网络请求 https://pub.flutter-io.cn/packages/dio_http_cache
  #  dio_http_cache: ^0.3.0
  # 监测网络状态 https://pub.flutter-io.cn/packages/connectivity_plus
  connectivity_plus: ^3.0.2
  # 路由管理 https://pub.flutter-io.cn/packages/fluro
  fluro: ^2.0.4
  # 状态管理 https://pub.flutter-io.cn/packages/provider
  provider: ^6.0.5
  # 屏幕参数适配 https://pub.flutter-io.cn/packages/flutter_screenutil
  flutter_screenutil: ^5.6.0
  # 常用工具类库（本地化 屏幕适配） https://pub.flutter-io.cn/packages/flustars
  #  flustars: ^2.0.1
  # flustars很久不维护，可以使用这个替代 https://pub.flutter-io.cn/packages/flustars_flutter3
  flustars_flutter3: ^3.0.0
  # 加密 https://pub.flutter-io.cn/packages/encrypt
  encrypt: ^5.0.1
  # 本地化存储 https://pub.flutter-io.cn/packages/shared_preferences
  shared_preferences: ^2.0.15
  # sq https://pub.flutter-io.cn/packages/sqflite
  sqflite: ^2.2.2
  # webview https://pub.flutter-io.cn/packages/webview_flutter
  webview_flutter: ^3.0.4 # flutter_echarts ^2.4.0 requires webview_flutter ^3.0.4.
  # url打开工具 https://pub.flutter-io.cn/packages/url_launcher
  url_launcher: ^6.1.7
  # 处理键盘事件 https://pub.flutter-io.cn/packages/keyboard_actions
  keyboard_actions: ^4.1.0
  # 时间格式转换 https://pub.flutter-io.cn/packages/date_format
  date_format: ^2.0.7
  # 图片缓存 https://pub.flutter-io.cn/packages/cached_network_image
  cached_network_image: ^3.2.3
  # 图片手势 https://pub.flutter-io.cn/packages/photo_view
  photo_view: ^0.14.0
  # 手机权限 https://pub.flutter-io.cn/packages/permission_handler
  permission_handler: ^10.2.0
  # 图片视频选择器(微信UI) https://pub.flutter-io.cn/packages/wechat_assets_picker
  wechat_assets_picker: ^8.3.0
  # 拍照与录像(微信UI) https://pub.flutter-io.cn/packages/wechat_camera_picker
  wechat_camera_picker: ^3.6.5
  # 获取安卓iOS设备信息 https://pub.flutter-io.cn/packages/device_info_plus
  device_info_plus: ^8.0.0
  # 获取版本信息 https://pub.flutter-io.cn/packages/package_info_plus
  package_info_plus: ^3.0.2
  # 图片库 https://pub.flutter-io.cn/packages/cupertino_icons
  cupertino_icons: ^1.0.5
  # toast https://pub.flutter-io.cn/packages/jhtoast
  jhtoast: ^1.2.0
  # 加载框 https://pub.flutter-io.cn/packages/bot_toast
  bot_toast: 4.0.3
  # 弹框 https://pub.flutter-io.cn/packages/fluttertoast
  fluttertoast: ^8.1.2
  # 底部弹出 日期选择器 单列多列  https://pub.flutter-io.cn/packages/flutter_picker
  flutter_picker: ^2.0.5
  # 下拉刷新(flutter_easyrefresh 3.0版本) https://pub.flutter-io.cn/packages/easy_refresh
  easy_refresh: ^3.2.0
  # 加载动画 https://pub.flutter-io.cn/packages/flutter_spinkit
  flutter_spinkit: ^5.1.0
  # 骨架屏 https://pub.flutter-io.cn/packages/shimmer
  shimmer: ^2.0.0
  # 下拉刷新 https://pub.flutter-io.cn/packages/flutter_easyrefresh
  flutter_easyrefresh: ^2.2.2
  # 下拉刷新 https://pub.flutter-io.cn/packages/pull_to_refresh
  pull_to_refresh: ^2.0.0
  # 列表悬浮头 https://pub.flutter-io.cn/packages/sticky_headers
  sticky_headers: ^0.3.0+2
  # 进度条 https://pub.flutter-io.cn/packages/percent_indicator
  percent_indicator: ^4.2.2
  # 侧滑删除 https://pub.flutter-io.cn/packages/flutter_slidable
  flutter_slidable: ^2.0.0
  # 小红点 https://pub.flutter-io.cn/packages/badges
  badges: ^2.0.3
  # 图表（EChart Flutter版） https://pub.flutter-io.cn/packages/graphic
  graphic: ^1.0.1
  # EChart 图表（缩放手势冲突，不稳定） https://pub.flutter-io.cn/packages/flutter_echarts
  flutter_echarts: ^2.4.0
  # 图表 （没有图例） https://pub.flutter-io.cn/packages/charts_flutter
  charts_flutter: ^0.12.0
  # 图表  https://pub.flutter-io.cn/packages/fl_chart
  #  fl_chart: ^0.55.2
  # 二维码生成 https://pub.flutter-io.cn/packages/qr_flutter
  qr_flutter: ^4.0.0
  # 二维码扫描(跳页面) https://pub.flutter-io.cn/packages/qr_code_scanner
  qr_code_scanner: ^1.0.1
  # 二维码扫描 https://pub.flutter-io.cn/packages/barcode_scan2
  barcode_scan2: ^4.2.2
  # 轮播 https://pub.flutter-io.cn/packages/flutter_swiper
  #  flutter_swiper: ^1.1.6
  # Flutter 轮播图 https://pub.flutter-io.cn/packages/flutter_swiper_null_safety_flutter3
  flutter_swiper_null_safety_flutter3: ^3.0.0   # flutter_swiper很久不维护，可以使用这个替代，2.0.0支持flutter3.0.0，3.0.0支持flutter3.3.0
  # 轮播 https://pub.flutter-io.cn/packages/carousel_slider
  carousel_slider: ^4.2.1
  # 城市选择列表 https://pub.flutter-io.cn/packages/azlistview
  azlistview: ^2.0.0
  # 汉字转拼音 https://pub.flutter-io.cn/packages/lpinyin
  lpinyin: ^2.0.3
  # 拖拽排序 https://pub.flutter-io.cn/packages/reorderables
  reorderables: ^0.5.1


  # ----- 废弃 -----
  # 图片选择(改为使用wechat_assets_picker) https://pub.flutter-io.cn/packages/image_picker
  #  image_picker: ^0.8.5+3
  #  # 加载框,华为手机有异常 https://pub.flutter-io.cn/packages/oktoast
  #  oktoast: ^3.1.4
  # 与flutter2.0冲突
  # 注：Flutter版本升到2.0.3之后，使用以下库写的图片多选选择器和mp_chart图表，暂时先注释了代码，如需查看可按tag v1.0.0版本环境运行查看
  # 相册多图选择 https://pub.flutter-io.cn/packages/photo
  #  photo: 0.4.8
  #  multi_image_picker: ^4.6.1
  # 图表（没有提示栏) https://pub.flutter-io.cn/packages/mp_chart
  #  mp_chart: ^0.3.1 #latest version
  # ----- 废弃 -----

dependency_overrides:
  # Pub get 没被覆盖，可删除或修复flutterSDk .pub-cache 中的所有依赖项
  # 运行命令：flutter pub cache clean 或 flutter pub cache repair 后删除 bin/cache路径下的lockfile重试
  # 如果引用了GitHub的库，要确保能访问GitHub

  # wechat_camera_picker引用，有警告
  camera: ^0.10.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/common/
    - assets/images/common/empty/
    - assets/images/funcMenu/
    - assets/images/newFeature/
    - assets/images/picture/
    - assets/images/popMenus/
    - assets/images/tab/
    - assets/images/service/
    - assets/images/demos/
    - assets/wechat/
    - assets/wechat/home/
    - assets/wechat/contacts/
    - assets/wechat/contacts/add/
    - assets/wechat/discover/
    - assets/wechat/discover/friends/
    - assets/wechat/mine/

    #假数据
    - lib/res/china.json
    - lib/res/wx_contacts.json
    - lib/res/wx_motion_top.json
    - lib/res/wx_friends_circle.json


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
